bem-contrib/bem-forms

- .bowerrc
- .jscsrc
- .jshint-groups.js
repeat @verybigman's idea
Fixes #19
> bowerrc: added .libs-* directories for bower

- common.blocks/label/label.bemhtml
- common.blocks/label/label.bh.js
- common.blocks/label/label.styl
- design/common.blocks/label/_theme/label_theme_simple.styl
> label: create block

- common.blocks/validation/_card/validation_card.vanilla.js
- common.blocks/validation/_email/validation_email.vanilla.js
- common.blocks/validation/_money/validation_money.vanilla.js
- common.blocks/validation/_numbers/validation_numbers.vanilla.js
- common.blocks/validation/_pattern/validation_pattern.vanilla.js
- common.blocks/validation/_required/validation_required.vanilla.js
- common.blocks/validation/validation.spec.js
- common.blocks/validation/validation.vanilla.js
> proposal tiny validation block

- common.blocks/form-field/_type/form-field_type_radio-group.browser.js
- common.blocks/form-field/_type/form-field_type_radio-group.deps.js
- desktop.bundles/index/index.bemjson.js
> radio-group field type

- common.blocks/form-field/_type/form-field_type_checkbox-group.browser.js
- common.blocks/form-field/_type/form-field_type_checkbox-group.deps.js
- desktop.bundles/index/index.bemjson.js
> checkbox-group field type

- common.blocks/form-field/_type/form-field_type_textarea.browser.js
- common.blocks/form-field/_type/form-field_type_textarea.deps.js
- desktop.bundles/index/index.bemjson.js
> add textarea field

- common.blocks/form-field/_message/form-field_message_popup.browser.js
- common.blocks/message/_type/message_type_popup.bemhtml
- common.blocks/message/_type/message_type_popup.browser.js
- common.blocks/message/_type/message_type_text.bemhtml
> popup and text in message is not control

- common.blocks/form-field/_required/form-field_required.browser.js
- common.blocks/form-field/_validate/form-field_validate_card.browser.js
- desktop.bundles/index/index.bemjson.js
> Messages from js params

- common.blocks/form/_has-validate/form_has-validate.browser.js
- common.blocks/validation/_card/validation_card.vanilla.js
> Setup messages for validations

- common.blocks/form-field/_has-validate/form-field_has-validate.browser.js
> add status checking for form-field

- common.blocks/checkbox-group/checkbox-group.bh.js
- common.blocks/checkbox/checkbox.bemhtml
- common.blocks/checkbox/checkbox.bh.js
- common.blocks/form-field/_type/form-field_type_hidden.bemhtml
- common.blocks/form-field/_type/form-field_type_hidden.bh.js
- common.blocks/form-field/form-field.bemhtml
- common.blocks/form-field/form-field.bh.js
- common.blocks/form-field/form-field.tmpl-specs/30-hidden.bemjson.js
- common.blocks/form-field/form-field.tmpl-specs/30-hidden.html
- common.blocks/input/__control/input__control.bemhtml
- common.blocks/input/__control/input__control.bh.js
- common.blocks/radio-group/radio-group.bemhtml
- common.blocks/radio/radio.bemhtml
- common.blocks/radio/radio.bh.js
- common.blocks/select/select.bh.js
- common.blocks/textarea/textarea.bemhtml
- common.blocks/textarea/textarea.bh.js
- desktop.bundles/examples/examples.bemjson.js
> hidden fallback and jscs fixes

- common.blocks/form/_has-validate/form_has-validate.browser.js
> Form getStatus method

- common.blocks/form/_has-validate/form_has-validate.browser.js
> Right form-fields collecting

- common.blocks/form/_has-validate/form_has-validate.browser.js
- common.blocks/form/form.browser.js
Fix ops usage in statements to unify style.
> fix `&&` and `||` usage in statements

- common.blocks/form-field/_has-validate/form-field_has-validate.browser.js
- common.blocks/form-field/_message/form-field_message.browser.js
- common.blocks/message/_type/message_type_popup.browser.js
- common.blocks/message/message.browser.js
- design/common.blocks/message/_theme/message_theme_islands.styl
> Messages methods and statuses

- common.blocks/form-field/_required/form-field_required.browser.js
- common.blocks/form-field/_validate/form-field_validate_card.browser.js
- common.blocks/validation/_card/validation_card.spec.js
- common.blocks/validation/_card/validation_card.vanilla.js
- common.blocks/validation/_email/validation_email.vanilla.js
- common.blocks/validation/_money/validation_money.vanilla.js
- common.blocks/validation/_numbers/validation_numbers.vanilla.js
- common.blocks/validation/_pattern/validation_pattern.vanilla.js
- common.blocks/validation/_required/validation_required.vanilla.js
- desktop.bundles/index/index.bemjson.js
> Unificate validation api

- common.blocks/form-field/_has-validate/form-field_has-validate.browser.js
> Missing call to __base in form-field_has-validate.browser.js

- common.blocks/validation/_card/validation_card.spec.js
- common.blocks/validation/_card/validation_card.vanilla.js
According to [wiki](http://en.wikipedia.org/wiki/Bank_card_number) these are proper ranges for IIN's.
> Fix card validation

- common.blocks/form/_has-validation/form_has-validation.bemhtml
Prevents browser built-in form validation.
> Disable browsers' form validation for form_has-validation

- common.blocks/form/_has-validation/form_has-validation.bemhtml
Oops. I thought you can omit the second argument...
> Fix "mod() must have two arguments"

- common.blocks/form-field/_has-validation/form-field_has-validation.deps.js
- common.blocks/form-field/_message/form-field_message_popup.deps.js
> fix typo in deps.js

- common.blocks/form-field/_message/form-field_message_popup.browser.js
- common.blocks/form/_message/form_message_popup.browser.js
> Add setAnchor method

- common.blocks/form-field/_type/form-field_type_attach.browser.js
- common.blocks/form-field/_type/form-field_type_attach.deps.js
- common.blocks/form-field/_type/form-field_type_checkbox-group.browser.js
- common.blocks/form-field/_type/form-field_type_checkbox.browser.js
- common.blocks/form-field/_type/form-field_type_input.browser.js
- common.blocks/form-field/_type/form-field_type_radio-group.browser.js
- common.blocks/form-field/_type/form-field_type_radio.browser.js
- common.blocks/form-field/_type/form-field_type_select.browser.js
- common.blocks/form-field/_type/form-field_type_textarea.browser.js
- desktop.bundles/index/index.bemjson.js
> feat(attach): support for attach block

- example.bundles/index/index.bemjson.js
> feat(*): structurate examples

- common.blocks/form-field/_required/form-field_required.bemhtml
- common.blocks/form-field/_validate/form-field_validate.bemhtml
- common.blocks/form-field/_validate/form-field_validate.bh.js
- common.blocks/form/_has-validation/form_has-validation.bh.js
- common.blocks/label/label.bh.js
- common.blocks/radio-group/radio-group.bh.js
I found some missed bh templates
> missed bh templates

- common.blocks/form-field/_type/form-field_type_attach.deps.js
- common.blocks/form-field/_type/form-field_type_checkbox-group.deps.js
- common.blocks/form-field/_type/form-field_type_checkbox.deps.js
- common.blocks/form-field/_type/form-field_type_input.deps.js
- common.blocks/form-field/_type/form-field_type_radio-group.deps.js
- common.blocks/form-field/_type/form-field_type_radio.deps.js
- common.blocks/form-field/_type/form-field_type_select.deps.js
- common.blocks/form-field/_type/form-field_type_textarea.deps.js
> feat(form-field) add mods invalid and dirty of controls

- common.blocks/form-field/form-field.bemhtml
- common.blocks/form-field/form-field.bh.js
- common.blocks/form-field/form-field.browser.js
- common.blocks/form/form.browser.js
> move _name mod to data-name attr

- common.blocks/form/form.browser.js
> Fix: getting invalid form-field in form

- common.blocks/form/form.browser.js
- common.blocks/form/form.deps.js
> Fix: this.nextTick in Form

- common.blocks/form/form.browser.js
> Restore Vow in Form

- common.blocks/form-field/_type/form-field_type_attach.browser.js
- common.blocks/form-field/_type/form-field_type_checkbox-group.browser.js
- common.blocks/form-field/_type/form-field_type_checkbox.browser.js
- common.blocks/form-field/_type/form-field_type_input.browser.js
- common.blocks/form-field/_type/form-field_type_radio-group.browser.js
- common.blocks/form-field/_type/form-field_type_radio.browser.js
- common.blocks/form-field/_type/form-field_type_select.browser.js
- common.blocks/form-field/_type/form-field_type_textarea.browser.js
- common.blocks/form-field/form-field.browser.js
- common.blocks/form-field/form-field.deps.js
> Strict mode for formField.getControl

- common.blocks/validation/_card/validation_card.browser.js
Регулярное выражения для карт типа "МИР". Используется для валидации карт на UI-форме, перед совершением платежа.
> Added. Card MIR validation pattern.
